apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-and-services
rules:
- apiGroups: [""]
  resources: ["pods", "services", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
