apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cron
spec:
  # execute every 5 hours
  schedule: "0 */5 * * *"

  # remove pods if it completes
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-job
            image: alpine:3.18.3
            args:
            - "/bin/date"
          restartPolicy: OnFailure
