apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kuard
      version: "2"
  template:
    metadata:
      labels: 
        name: kuard
        version: "2"
    spec:
      containers:
      - name: kuard
        image: "gcr.io/kuar-demo/kuard-amd64:green"
