apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: kuard
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
