from os import path

import yaml

from kubernetes import client, config

# refer to
# https://github.com/kubernetes-client/python/blob/master/examples/deployment_create.py
# and
# https://github.com/kubernetes-client/python/blob/master/examples/deployment_crud.py
# 
# create a deployment

namespace="fuming-poc"

config.load_kube_config()
with open(path.join(path.join(path.dirname(__file__), "nginx-deployment.yaml"))) as f:
  dep = yaml.safe_load(f)
  k8s_app_v1 = client.AppsV1Api()
  resp = k8s_app_v1.create_namespaced_deployment(body=dep, namespace=namespace)
  print("Deployment created. status='%s'" % resp.metadata.name)

