apiVersion: v1
kind: Service
metadata:
  labels:
    run: jupyter
  name: jupyter
  namespace: jupyter
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    run: jupyter

