apiVersion: v1
kind: Pod
metadata:
  name: kuard-allowed
spec:
  securityContext:
    supplementalGroups:
      - 199
    fsGroup: 199
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard-allowed
      securityContext:
        runAsUser: 199
        runAsGroup: 199
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP




