apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.sh: |
    # 須先更新 apt 和套件才能安裝 ping
    apt update -y
    apt upgrade -y
    apt install iputils-ping -y
   
    # 需要等待 readiness 檢查完才能夠解析到 Mongo 的名稱
    #!/bin/bash
    until ping -c 1 ${HOSTNAME}.mongo; do
      echo "waiting for DNS (${HOSTNAME}.mongo)..."
      sleep 2
    done
 
    until /usr/bin/mongo --eval 'printjson(db.serverStatus())'; do
      echo "connect to local mongo..."
      sleep 2
    done
    echo "connected to local."

    HOST=mongo-0.mongo:27017

    until /usr/bin/mongo --host=${HOST} --eval 'printjson(db.serverStatus())'; do
      echo "connect to remove mongo..."
      sleep 2
    done
    echo "connected to remote."
    
    if [[ "${HOSTNAME}" != 'mongo-0' ]]; then
      until /usr/bin/mongo --host=${HOST} --eval="printjson(rs.status())" | grep -v "no replset config has been received"; do
        echo "waiting for replication set initialization"
        sleep 2
      done
      echo "adding self to mongo-0"
      /usr/bin/mongo --host=${HOST} --eval="printjson(rs.add('${HOSTNAME}.mongo'))"
    fi
 
    if [[ "${HOSTNAME}" == 'mongo-0' ]]; then
      echo "initializing replica set"
      /usr/bin/mongo --eval="printjson(rs.initiate({'_id':'rs0', 'members':[{'_id':0,'host':'mongo-0.mongo:27017'}]}))"
    fi
    echo "initialized"
    
    while true; do
      sleep 3600
    done
