apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    volume: my-volume
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  capacity:
    storage: 1Gi
  nfs:
    server: 10.186.0.53
    path: "/exports"
