apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:  
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
#  selector:
#    matchLabels:
#      volume: my-volume
  volumeName: database-pv
  storageClassName: ""
