apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls-1
spec: 
  containers:
    - name: kuard-tls-1
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      volumeMounts:
      - name: tls-certs
        mounthPath: "/tls"
        readOnly: true
  imagePullSecrets:
  - name: my-image-pull-secret
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls-1
