apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kuard
  
spec: 
  revisionHistoryLimit: 14 # only 14 revision records are kept
  selector:
    matchLabels:
      run: kuard
  replicas: 3
  template:
    metadata:
      labels:
        run: kuard
      annotations:
        kubernetes.io/change-cause: "Update to blue kuard"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue

