apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: kuard
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
